config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get  'pages/test'
  get  'pages/index'
  get  'users/login'
  get  'pages/about_us'
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        Rails.logger.info("##########################################################################################")
        Rails.logger.info("##########################################################################################")
        Rails.logger.info("##########################################################################################")
        Rails.logger.info("############Agrega un parrafo en la vista index.html.erb con el texto: Rails es genial!!!################")
        Rails.logger.info("##########################################################################################")
        Rails.logger.info("##########################################################################################")
        Rails.logger.info("##########################################################################################")
    end

    def test
        
    end

    def about_us
        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def login
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>SecondApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

 <body>
    <div id="page-wrapper">

			<!-- Header -->
				<div id="header">
					<!-- Nav -->
						<nav id="nav">
							<ul>
								<li><%= link_to 'Index', pages_index_path %></li>
								<li><%= link_to 'Test', pages_test_path %><li>
								<li><%= link_to 'Log In', users_login_path %></li>
								<li><%= link_to 'About Us', pages_about_us_path %></li>
							</ul>
						</nav>

				</div>

			<!-- Main -->
				<div class="wrapper style1">

					<div class="container">
						<article id="main" class="special">
              <%= yield %>
						</article>
					</div>

				</div>

			<!-- Footer -->
				<div id="footer">
					<div class="container">
						<div class="row">

							
						</div>
						<hr />
						<div class="row">
							<div class="col-12">

								

								<!-- Copyright -->
									<div class="copyright">
										<ul class="menu">
											<li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
										</ul>
									</div>

							</div>

						</div>
					</div>
				</div>

		</div>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
 
</html>

app/views/pages/about_us.html.erb
<p> Commodo id natoque malesuada sollicitudin elit suscipit. Curae suspendisse mauris posuere accumsan massa
    posuere lacus convallis tellus interdum. Amet nullam fringilla nibh nulla convallis ut venenatis purus
    lobortis. Auctor etiam porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum
    consequat integer interdum integer purus sapien. Nibh eleifend nulla nascetur pharetra commodo mi augue
    interdum tellus. Ornare cursus augue feugiat sodales velit lorem. Semper elementum ullamcorper lacinia
    natoque aenean scelerisque vel lacinia mollis quam sodales congue.</p>

app/views/pages/index.html.erb
<p> Rails es genial!!! <p>

app/views/pages/test.html.erb
<%= image_tag '/helios.jpg' %>